version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.1
    environment:
      - 'discovery.type=single-node'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
  plugin:
    image: firstandthird/node:8.9-3-dev
    environment:
      ELASTICSEARCH_HOST: 'elasticsearch'
    depends_on:
      - 'elasticsearch'
    volumes:
      - './:/home/app/src'
